[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "./src/"

[build-system]
requires = [
    "setuptools >= 69",
    ]
build-backend = "setuptools.build_meta"

[project]
name = "gicinema"
version = "0.0.1"
dependencies = [
    "jinja2"
]